# xDs values
global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  # Might want to point the xds values to the global values or vice versa
  xds:
    port:
    cluster:

xds:
  image: 'docker.production.deciphernow.com/deciphernow/gm-xds:0.2.9'
  imagePullPolicy: Always
  version: 0.2.6
  cluster: greymatter
  #host: 'xds.greymatter.svc.cluster.local'
  port: 18000
  use_zk: 'true'
  logging_level: info
  zk_base_path: '/services'
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

sidecar:
  version: 0.7.1
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.7.1'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    - type: value
      name: ingress_use_tls
      value: 'true'
    - type: value
      name: ingress_ca_cert_path
      value: '/etc/proxy/tls/sidecar/ca.crt'
    - type: value
      name: ingress_cert_path
      value: '/etc/proxy/tls/sidecar/server.crt'
    - type: value
      name: ingress_key_path
      value: '/etc/proxy/tls/sidecar/server.key'
    - type: value
      name: metrics_port
      value: '8080'
    - type: value
      name: port
      value: '8443'
    - type: value
      name: kafka_zk_discover
      value: 'false'
    - type: value
      name: kafka_server_connection
      value: 'kafka:9091,kafka2:9091'
    - type: value
      name: kafka_enabled
      value: 'false'
    - type: value
      name: kafka_topic
      value: 'xds'
    - type: value
      name: metrics_key_function
      value: 'depth'
    - type: value
      name: proxy_dynamic
      value: 'false'
    - type: value
      name: obs_enabled
      value: 'false'
    - type: value
      name: obs_enforce
      value: 'false'
    - type: value
      name: obs_full_response
      value: 'false'
  # Setcreate_sidecar_secret to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    # name: sidecar
    # ca: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # cert: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # key: |-
    #   -----BEGIN RSA PRIVATE KEY-----
    #   ...
    #   -----END RSA PRIVATE KEY-----
