apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: {{ .Release.Namespace }}
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "DEBUG"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/config/bootstrap.crt"
      trust_domain = "{{ .Values.spire.trustDomain }}"
      enable_sds = true
    }

    plugins {
      NodeAttestor "k8s_sat" {
        plugin_data {
          # NOTE: Change this to your cluster name
          cluster = "{{ .Values.spire.clusterName }}"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          kubelet_read_only_port = "10250"
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }
    }

  bootstrap.crt: |-
{{ .Values.spire.certs.bootstrap.crt | indent 4 }}