apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-client
  labels:
    app: spire-client
spec:
  selector:
    matchLabels:
      app: spire-client
  template:
    metadata:
      labels:
        app: spire-client
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: client
          image: ad-dbn-stdec001.citadelgroup.com/spiffe-io/spire-k8s
          args: ["/bin/bash", "-c", "sleep infinity"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
