{{- if .Values.spire.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.spire.server.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}