apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZG9ja2VyLmdyZXltYXR0ZXIuaW8iOiB7ImF1dGgiOiAiZW05bExtMWpZMjl5YldsamEwQm5jbVY1YldGMGRHVnlMbWx2T2pJd09URXdNME5oY2c9PSJ9fX0=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: kafka
  creationTimestamp: "2021-02-02T15:24:15Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-02-02T15:24:15Z"
  name: docker.secret
  namespace: kafka 
  resourceVersion: "768"
  selfLink: /api/v1/namespaces/kafka/secrets/docker.secret
  uid: 3e379bd5-cff6-449a-8695-564e2d3a6c28
type: kubernetes.io/dockerconfigjson
