# Source: kafka/charts/zookeeper/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-observables-zookeeper-2
  namespace: kafka
  labels:
    app.kubernetes.io/name: zookeeper-2
    helm.sh/chart: zookeeper-5.14.3
    app.kubernetes.io/instance: kafka-observables
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: zookeeper-2
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8081
    - name: proxy
      port: 2180
    - name: follower
      port: 2889
    - name: election
      port: 3889

    #- name: tcp-client
    #  port: 2181
    #  targetPort: client
    #- name: follower
    #  port: 2888
    #  targetPort: follower
    #- name: tcp-election
    #  port: 3888
    #  targetPort: election
  selector:
    app.kubernetes.io/name: zookeeper-2
    app.kubernetes.io/instance: kafka-observables
    app.kubernetes.io/component: zookeeper-2
