{{- $top := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs
data:
  empty: |
    hello world
{{- range $name, $service := .Values.oldtown.services }}
---
{{- $serviceConfig := dict "serviceName" $service.serviceName "route" (tpl $service.route $top) "port" $top.Values.oldtown.proxyPort "zone" $top.Values.oldtown.zone }}
{{- include "mesh_svc_config" $serviceConfig }}
...
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-mesh-config
  namespace: default
  mesh-config: domain
data:
  domain.json: |
    {
        "domain_key": "domain-*",
        "zone_key": "zone-default-zone",
        "name": "*",
        "port": 8080,
        "redirects": null,
        "gzip_enabled": false,
        "cors_config": null,
        "aliases": null,
        "force_https": false,
        "checksum": "649c96afcec75f0907d03bf4e7d112201c3a99e799941ed0d4b37df3bfe56328"
    }
...