# hi test
{{- $top := . }}
{{- range $name, $service := .Values.oldtown.services }}
---
{{- $serviceConfig := dict "serviceName" $service.serviceName "route" (tpl $service.route $top) "port" $top.Values.oldtown.proxyPort "zone" $top.Values.oldtown.zone }}
{{- include "mesh_svc_config" $serviceConfig }}
...
{{- end}}