apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.oldtown.name }}
spec:
  selector:
    app: {{ .Values.oldtown.name }}
  ports:
  - port: {{ .Values.oldtown.containerPort }}
    targetPort: {{ .Values.oldtown.containerPort }}
