apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.oldtown.name}}-init
spec:
  template:
    metadata:
      name: {{.Values.oldtown.name}}-init
    spec:
      restartPolicy: "OnFailure"
      containers:
        - image: registry.gitlab.com/alexkreidler/gm-cli-docker:latest
          name: {{ .Values.oldtown.name }}-init
          command: ["/tmp/bootstrap/bootstrap.sh"]
          env:
          {{- include "envvars" (dict "envvar" .Values.oldtown.init.envvars "top" $) | indent 12 }}
          volumeMounts:
          {{- range $name, $service := .Values.oldtown.services }}
            - name: mesh-config-volume-{{$service.serviceName}}
              mountPath: /etc/config/mesh/{{$service.serviceName}}
          {{- end }}
            - name: mesh-config-volume-domain
              mountPath: /etc/config/mesh/domain
            - name: bootstrap-script-volume
              mountPath: /tmp/bootstrap
      volumes:
        {{- range $name, $service := .Values.oldtown.services }}
        - name: mesh-config-volume-{{ $service.serviceName }}
          configMap:
            name: {{ $service.serviceName }}-mesh-config
        {{- end }}
        - name: mesh-config-volume-domain
          configMap:
            name: domain-mesh-config
        - name: bootstrap-script-volume
          configMap:
            name: bootstrap-script
            defaultMode: 0777
      imagePullSecrets:
        - name: dev.docker.secret