# Default values for oldtown.
global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  # XDS will be replaced with oldtown eventually
  xds:
    port: 18000
    cluster: greymatter
  oldtown:
    version: latest

spire:
  trustDomain: deciphernow.com
  clusterName: k8s
  server:
    name: spire-server

    # This spire Docker registry requires an explicit version, it doesn't have a tag latest
    image: gcr.io/spiffe-io/spire-server:0.8.1 #0.7.3
    # Registration API UDS location
    registrationAPIPath: /tmp/spire/registration/registration.sock
    registrationAPIDir: /tmp/spire/registration
    # Spire server config file location
    configFilePath: /run/spire/config/server.conf
    configFileDir: /run/spire/config
  agent:
    image: gcr.io/spiffe-io/spire-agent:0.8.1

  certs:
    # This certificate must match the trust domain specified above
    bootstrap:
      # ca: |-
      #   -----BEGIN CERTIFICATE-----
      #   ...
      #   -----END CERTIFICATE-----
      crt: |-
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
      # crt: |- 
      #   -----BEGIN CERTIFICATE-----
      #   MIIBzjCCAVWgAwIBAgIBADAKBggqhkjOPQQDAzAeMQswCQYDVQQGEwJVUzEPMA0G
      #   A1UEChMGU1BJRkZFMB4XDTE5MDcyNDIwNDgxMVoXDTE5MDcyNTIwNDgyMVowHjEL
      #   MAkGA1UEBhMCVVMxDzANBgNVBAoTBlNQSUZGRTB2MBAGByqGSM49AgEGBSuBBAAi
      #   A2IABAKUAso8KnSr2Dq2SbNxSAtRArwWWaSye4p8LgZVzGVxe8Blc2Clq3P4JB8/
      #   gbFZ+eyuAZrNLXRp5pc3LcpyBFr9I0uSqb5tSYvuJojObvmMoDyxH4Lq1NxO4nv8
      #   jQoa8KNnMGUwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
      #   BBYEFA0uf/LNhd+RVTwArBT7WpBZSFrmMCMGA1UdEQQcMBqGGHNwaWZmZTovL2Rl
      #   Y2lwaGVybm93LmNvbTAKBggqhkjOPQQDAwNnADBkAjBgXowK9p5RKE0BcOwHhyjQ
      #   +zIVu8S5FrXiKZBQOcX9wRgCIztb03HMtE52mjkozUYCMHv0XTpLS3QXceoSnGkS
      #   ZQ3K7DFR97ZTz5iOofykjx1jzpvQvfEpHIa4Rm7SIFl5QQ==
      #   -----END CERTIFICATE-----
      # key: |-
      #   -----BEGIN EC PRIVATE KEY-----
      #   MIGkAgEBBDAg2LbulXzQX1NF+2Di0RKzMWfEGioBhh/fFpx7yOEqka//TpaeU3O5
      #   QJRZXdWHKuagBwYFK4EEACKhZANiAARaMH6dIZLEhiLOdvzjG7lYYNmPzScvtbVz
      #   fN/jxaHLSZrtjuYIErN9CSuAOC4jiPRn7T+0Mf+vyC060susim4zBYeh7i9tUEW1
      #   7W+Ppe3pZ4TyVfBwK8uz+Zya8+pUr2M=
      #   -----END EC PRIVATE KEY-----