# Grey Matter Service Level Objectives Defaults

global:
  # Used as imagePullSecrets value
  image_pull_secret: docker.secret
  # Deployment environment, one of "eks", "kubernetes", or "openshift"
  environment: openshift
  # Used to configure control and control-api environment variables
  zone: zone-default-zone
  # Whether to use consul for service discovery
  consul:
    enabled: false
    host: ''
    port: 8500
    edge_port: 10808
  control:
    # Port for Grey Matter Control. Used in sidecar envvars
    port: 50000
    # The label Control uses to find pods to include in the mesh
    cluster_label: greymatter.io/control
  # Whether or not to use spire for cert management and the trust domain
  spire:
    enabled: false
    trust_domain: quickstart.greymatter.io
    path: '/run/spire/socket/agent.sock'
  # Configures the init container used to wait on various deployments to be ready
  waiter:
    image: docker.greymatter.io/internal/k8s-waiter:latest
    service_account:
      name: waiter-sa
  # Global sidecar configuration (supports global version and envvars)
  sidecar:
    version: 1.5.1
  # To use the global certs or not
  global_certs:
    enabled: true
  release:
    # release.production: true will increase all (except control-api) replicas to the default_replicas.  Otherwise the default for each chart will be used
    production: false
    default_replicas: 3
lad:
  name: "lad"
  # LAD version
  version: 1.0.0-rc.1
  image: "docker.greymatter.io/development/sense-lad:{{ .Values.lad.version }}"
  # When to pull container images, used in the deployment
  image_pull_policy: IfNotPresent
  container_port: 8080
  replicas: 1
  # CPU and memory limits for the LAD service
  resources:
    limits:
      cpu: '4'
      memory: 5Gi
    requests:
      cpu: '2'
      memory: 2Gi
  envvars:
    lad_inference_threads:
      type: value
      value: "3"
    lad_training_threads:
      type: value
      value: "3"
   
# Sidecar configuration for LAD
sidecar:
  version: '{{- $.Values.global.sidecar.version | default "latest" }}'
  image: 'docker.greymatter.io/development/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
  # Port where the proxy will listen
  port: 10808
  # Port where the proxy will expose metrics
  metrics_port: 8081
  secret:
    enabled: true
    secret_name: sidecar-certs
    mount_point: /etc/proxy/tls/sidecar
    secret_keys:
      ca: ca.crt
      cert: server.crt
      key: server.key
  # Overrides global.sidecar.envvars
  envvars:
    xds_cluster:
      type: value
      value: '{{ .Values.lad.name }}'
  # When to pull images, used in the deployment
  image_pull_policy: IfNotPresent
  # CPU and memory limits for the sidecar
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
