kind: ConfigMap
apiVersion: v1
metadata:
  name: jwt-users
  namespace: {{ .Release.Namespace }}
data:
{{- if and .Values.jwt.deployment_type (ne .Values.jwt.deployment_type "gov") }}
  users.json: |-
    {
        "users": [
        {
        "label": "CN=quickstart,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
        "values": {
            "email": [
                "quickstart@deciphernow.com"
            ],
            "org": [
                "www.deciphernow.com"
            ],
            "privilege": [
                "root"
            ]
            }
        }]
    }
{{ else }}
  AOs.json: |-
    [
        {
            "userDN": "CN=quickstart,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US",
            "diasUserGroups": {
                "projects": [
                    {}
                ]
            },
            "whitePageAttributes": {
                "firstName": "quick",
                "surName": "start",
                "uid": "",
                "companyName": "",
                "telephoneNumber": "123-123-1234 1234",
                "icEMail": "quickstart@ic.com",
                "siprnetEmail": "quickstart@sipr.com",
                "niprnetEmail": "quickstart@nipr.com"
            },
            "userClearance": {
                "clearance": "U",
                "clearanceRank": 0,
                "citizenship": "USA",
                "formalAccess": []
            },
            "gimmeeAttributes": {
                "organization": "",
                "topic": [],
                "region": [],
                "groups": [],
                "isAICP": false,
                "communityType": null,
                "organizationalPath": null
            },
            "localUserGroups": {
                "projects": []
            },
            "nShare": {},
            "status": "SUCCESS",
            "f_macs": {
                "negate": [
                ],
                "as_is": []
            },
            "f_oc_org": {
                "as_is": []
            },
            "f_accms": {
                "negate": [
                ],
                "as_is": []
            },
            "f_clearance": {
                "as_is": [
                    "u"
                ]
            },
            "f_regions": {
                "as_is": []
            },
            "f_missions": {
                "as_is": []
            },
            "f_share": {
                "as_is": [ 
                ]
            },
            "f_sci_ctrls": {
                "negate": [
                ],
                "as_is": []
            }
        }
    ]
  admins.json: |-
    [
        "CN=quickstart,OU=Engineering,O=Decipher Technology Studios,=Alexandria,=Virginia,C=US"
    ]
{{ end }}