kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ .Values.jwt.name | default "jwt-security"  }}
    namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.global.exhibitor.replicas | default 1 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.jwt.name | default "jwt-security"  }}
      deployment: {{ .Values.jwt.name | default "jwt-security"  }}
  template:
    metadata:
      labels:
        app: {{ .Values.jwt.name | default "jwt-security"  }}
        deployment: {{ .Values.jwt.name | default "jwt-security"  }}
    spec:
      containers:
      - name: jwt-security
        image: {{ tpl .Values.jwt.image $ | quote }}
        imagePullPolicy: {{ .Values.jwt.imagePullPolicy }}
        {{- if .Values.jwt.resources }}
        resources:
{{ toYaml .Values.jwt.resources | indent 10 }}
        {{- end }}
        {{- if .Values.jwt.command }}
        command:
{{ toYaml .Values.jwt.command | indent 8 }}
        args:
{{ toYaml .Values.jwt.args | indent 8 }}
        {{- end }}

        env:
      {{- range $envvar := .Values.jwt.envvars }}
      {{- $envName := $envvar.name | upper | replace "." "_" | replace "-" "_" }}
        {{- if eq $envvar.type "secret" }}
        - name: {{ $envName }}
          valueFrom:
            secretKeyRef:
              name: {{ $envvar.secret }}
              key: {{ $envvar.key }}
        {{- else if eq $envvar.type "value" }}
        - name: {{ $envName }}
          value: {{ $envvar.value | quote }}
        {{- end }}
      {{- end  }}   
        - name: REDIS_HOST
          value: localhost
        - name:  REDIS_PORT
          value: "6380"
        - name: REDIS_DB
          value: {{ .Values.jwt.redis_db | quote }}
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.secret_name }}
              key: password
        volumeMounts:
        - name: jwt-users
          mountPath: {{ .Values.jwt.users_mount_point }}
      
      - name: sidecar
        image: {{ tpl .Values.sidecar.image $ | quote }}
        imagePullPolicy: {{ .Values.sidecar.imagePullPolicy }}
        env:
        {{- include "greymatter.envvars" . | indent 8 }}
        {{- if .Values.sidecar.resources }}
        - name: ENVOY_CONFIG
          value: |-
            DQphZG1pbjoNCiAgYWNjZXNzX2xvZ19wYXRoOiAiL2Rldi9zdGRvdXQiDQogIGFkZHJlc3M6DQogICAgc29ja2V0X2FkZHJlc3M6DQogICAgICBhZGRyZXNzOiAwLjAuMC4wDQogICAgICBwb3J0X3ZhbHVlOiA4MDAxDQoNCmR5bmFtaWNfcmVzb3VyY2VzOg0KICBhZHNfY29uZmlnOg0KICAgIGFwaV90eXBlOiBHUlBDDQogICAgZ3JwY19zZXJ2aWNlczoNCiAgICAgIGVudm95X2dycGM6DQogICAgICAgIGNsdXN0ZXJfbmFtZTogeGRzX2NsdXN0ZXINCiAgY2RzX2NvbmZpZzoNCiAgICBhZHM6IHt9DQogIGxkc19jb25maWc6DQogICAgYWRzOiB7fQ0KDQpub2RlOg0KICBjbHVzdGVyOiBqd3Qtc2VjdXJpdHkNCiAgaWQ6IGRlZmF1bHQNCiAgbG9jYWxpdHk6DQogICAgcmVnaW9uOiBkZWZhdWx0LXJlZ2lvbg0KDQpzdGF0aWNfcmVzb3VyY2VzOg0KICBsaXN0ZW5lcnM6DQogIC0gbmFtZTogcmVkaXNfbGlzdGVuZXINCiAgICBhZGRyZXNzOg0KICAgICAgc29ja2V0X2FkZHJlc3M6DQogICAgICAgIGFkZHJlc3M6IDAuMC4wLjANCiAgICAgICAgcG9ydF92YWx1ZTogNjM4MA0KICAgIGZpbHRlcl9jaGFpbnM6DQogICAgLSBmaWx0ZXJzOg0KICAgICAgLSBuYW1lOiBlbnZveS50Y3BfcHJveHkNCiAgICAgICAgY29uZmlnOg0KICAgICAgICAgIHN0YXRfcHJlZml4OiBpbmdyZXNzX3JlZGlzDQogICAgICAgICAgY2x1c3RlcjogcmVkaXNfY2x1c3Rlcg0KICAgICAgICAgIGFjY2Vzc19sb2c6DQogICAgICAgICAgICAtIG5hbWU6IGVudm95LmZpbGVfYWNjZXNzX2xvZw0KICAgICAgICAgICAgICBjb25maWc6DQogICAgICAgICAgICAgICAgcGF0aDogIi90bXAvcmVkaXNfY2x1c3Rlci5sb2ciDQogIGNsdXN0ZXJzOg0KICAtIG5hbWU6IHhkc19jbHVzdGVyDQogICAgY29ubmVjdF90aW1lb3V0OiAwLjI1cw0KICAgIHR5cGU6IFNUUklDVF9ETlMNCiAgICBsYl9wb2xpY3k6IFJPVU5EX1JPQklODQogICAgaHR0cDJfcHJvdG9jb2xfb3B0aW9uczoge30NCiAgICBsb2FkX2Fzc2lnbm1lbnQ6DQogICAgICBjbHVzdGVyX25hbWU6IHhkc19jbHVzdGVyDQogICAgICBlbmRwb2ludHM6DQogICAgICAtIGxiX2VuZHBvaW50czoNCiAgICAgICAgLSBlbmRwb2ludDoNCiAgICAgICAgICAgIGFkZHJlc3M6DQogICAgICAgICAgICAgIHNvY2tldF9hZGRyZXNzOg0KICAgICAgICAgICAgICAgIGFkZHJlc3M6IGNvbnRyb2wuZGVmYXVsdC5zdmMNCiAgICAgICAgICAgICAgICBwb3J0X3ZhbHVlOiA1MDAwMA0KICAtIG5hbWU6IHNwaXJlX2FnZW50DQogICAgY29ubmVjdF90aW1lb3V0OiAwLjI1cw0KICAgIGh0dHAyX3Byb3RvY29sX29wdGlvbnM6IHt9DQogICAgaG9zdHM6DQogICAgICAtIHBpcGU6DQogICAgICAgICAgcGF0aDogL3J1bi9zcGlyZS9zb2NrZXRzL2FnZW50LnNvY2sNCiAgLSBuYW1lOiByZWRpc19jbHVzdGVyDQogICAgY29ubmVjdF90aW1lb3V0OiAxcw0KICAgIHR5cGU6IFNUUklDVF9ETlMNCiAgICBsYl9wb2xpY3k6IFJPVU5EX1JPQklODQogICAgbG9hZF9hc3NpZ25tZW50Og0KICAgICAgY2x1c3Rlcl9uYW1lOiByZWRpc19jbHVzdGVyDQogICAgICBlbmRwb2ludHM6DQogICAgICAtIGxiX2VuZHBvaW50czoNCiAgICAgICAgLSBlbmRwb2ludDoNCiAgICAgICAgICAgIGFkZHJlc3M6DQogICAgICAgICAgICAgIHNvY2tldF9hZGRyZXNzOg0KICAgICAgICAgICAgICAgIGFkZHJlc3M6IHJlZGlzLmRlZmF1bHQuc3ZjDQogICAgICAgICAgICAgICAgcG9ydF92YWx1ZTogMTQ0Mw0K
        resources:
{{ toYaml .Values.sidecar.resources | indent 10 }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: proxy
          protocol: TCP
        - containerPort: 8081
          name: metrics
          protocol: TCP
        {{- if .Values.global.spire.enabled }}
        volumeMounts:
        {{- include "sidecar_volume_mounts" . | indent 8 }}
        {{- else if and (not .Values.global.spire.enabled) (.Values.global.mesh_tls.use_provided_certs) }}
        volumeMounts:
        {{- include "sidecar_volume_certs_mount" . | indent 8 }}
        {{- end }}
      {{- if .Values.global.consul.enabled }}
      {{- $data := dict "Values" .Values "ServiceName"  (default "jwt-security"  .Values.jwt.name) }}
      {{- include "consul.agent" $data | nindent 6 }}
      {{- end }}
      imagePullSecrets:
        - name: docker.secret
      volumes:
      {{- if .Values.global.spire.enabled }}
      {{- include "sidecar_volumes" . | indent 6 }}
      {{- else if and (not .Values.global.spire.enabled) (.Values.global.mesh_tls.use_provided_certs) }}
      volumes:
      {{- include "sidecar_certs_volumes" . | indent 6 }}
      {{- end }}
      - name: jwt-users
        configMap:
          name: {{ .Values.jwt.users_cg_name }}
      {{- if .Values.global.consul.enabled }}
      - name: data-consul
        emptyDir: {}
      - name: config-consul
        emptyDir: {}
      {{- end }}
