kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.redis.name | default "redis" }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: server
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: redis-ingres
      port: 1443
      protocol: TCP
      targetPort: 1443
  selector:
    app: {{ .Values.redis.name | default "redis" }}
  sessionAffinity: None
  type: ClusterIP
