# Source: kafka/templates/kafka-metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-observables-metrics
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-12.16.2
    app.kubernetes.io/instance: kafka-observables
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
  annotations:
    
    prometheus.io/path: /metrics
    prometheus.io/port: '9308'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9308
      protocol: TCP
      targetPort: metrics
      nodePort: null
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka-observables
    app.kubernetes.io/component: metrics