version: '2'

services:
  gm-control:
    networks:
      mesh:
        aliases:
          - gmcontrol
    image: deciphernow/gm-control:latest
    ports:
      - "50000:50000"
    environment:
      - GM_CONTROL_CONSOLE_LEVEL=debug
      - GM_CONTROL_API_KEY=xxx
      - GM_CONTROL_API_ZONE_NAME=default-zone
      - GM_CONTROL_API_SSL=false
      - GM_CONTROL_API_HOST=oldtown:5555
      - GM_CONTROL_CMD=file
      - GM_CONTROL_FILE_FORMAT=yaml
      - GM_CONTROL_FILE_FILENAME=/app/routes.yaml
      - GM_CONTROL_XDS_RESOLVE_DNS=true
      - GM_CONTROL_XDS_ADS_ENABLED=true
    depends_on:
      - oldtown

  proxy:
    networks:
      - mesh
    image: deciphernow/gm-proxy:0.7.2
    ports:
      - "8080:8080"
      - "8888:8888"
      - "8001:8001"
    environment:
      - PROXY_DYNAMIC=true
      - XDS_CLUSTER=client-server
      - XDS_NODE_ID=default-node
      - XDS_HOST=gmcontrol
      - XDS_PORT=50000
      - ENVOY_ADMIN_LOG_PATH=/dev/stdout
    depends_on:
      - gm-control
      - example-service

  example-service:
    networks:
      - mesh
    image: deciphernow/example-service:2.0
    ports:
      - "3000:3000"

  oldtown:
    networks:
      mesh:
        aliases:
          - oldtown
    image: deciphernow/oldtown:latest
    ports:
      - "5555:5555"
    environment:
      - OLDTOWN_LOG_LEVEL=debug
      - OLDTOWN_ADDRESS=0.0.0.0:5555
      - OLDTOWN_ORG_KEY=deciphernow
      - OLDTOWN_PERSISTER_TYPE=file
      - OLDTOWN_PERSISTER_PATH=/control-plane/oldtown_backend.json
    volumes:
      - ./oldtown_backend.json:/control-plane/oldtown_backend.json

networks:
  mesh: {}
