apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.control.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.control.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.control.name }}
      deployment: {{ .Values.control.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.control.name }}
        deployment: {{ .Values.control.name }}
        run: {{ .Values.control.name }}
    spec:
      serviceAccountName: {{ .Values.control.name }}-sa
      containers:
        - name: {{ .Values.control.name }}
          image: {{ tpl .Values.control.image $ }}
          imagePullPolicy: {{ .Values.control.imagePullPolicy }}
          env:
            {{- include "envvars" (dict "envvar" .Values.control.envvars "top" $) | indent 12 }}
          ports:
            - name: grpc
              containerPort: 50000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: ensure-oldtown
          image: alexkreidler/k8s-waiter
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: oldtown
            - name: POST_DELAY
              value: "10"
      imagePullSecrets:
        - name: docker.secret