apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.control.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.control.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.control.name }}
      deployment: {{ .Values.control.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.control.name }}
        deployment: {{ .Values.control.name }}
        run: {{ .Values.control.name }}
    spec:
      serviceAccountName: {{ .Values.control.name }}-sa
      containers:
        - name: {{ .Values.control.name }}
          image: {{ tpl .Values.control.image $ }}
          imagePullPolicy: {{ .Values.control.imagePullPolicy }}
          env:
            {{- include "envvars" (dict "envvar" .Values.control.envvars "top" $) | indent 12 }}
          ports:
            - name: http
              containerPort: 50000
              protocol: TCP
          # TODO:
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: ensure-oldtown
          image: busybox:1.28
          command: ['sh', '-c', 'env; until nslookup oldtown; do echo "Waiting for oldtown ..."; sleep 2; done; echo "Waiting 20 seconds"; sleep 20;'] #'for i in {1..100}; do sleep 1; if dig myservice; then exit 0; fi; done; exit 1']
          envvars:
            {{- include "envvars" (dict "envvar" .Values.control.envvars "top" $) | indent 12 }}
      imagePullSecrets:
        - name: docker.secret
      # volumes:
      #   - name: "config"
      #     configMap:
      #       name: "config"