kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
      deployment: edge
  template:
    metadata:
      labels:
        app: edge
        deployment: edge
    spec:
      containers:
      - name: edge
        image: {{ tpl .Values.sidecar.image $ | quote }}
        imagePullPolicy: {{ .Values.sidecar.imagePullPolicy }}
        {{- if .Values.edge.resources }}
        resources:
{{ toYaml .Values.edge.resources | indent 10 }}
        {{- end }}
        env:
        {{- include "greymatter.envvars" . | indent 8 }}
        # - name: ZK_ADDRS
        #   value: {{ template "greymatter.exhibitor.address" . }}
        # - name: ZK_ANNOUNCE_PATH
        #   value: {{ .Values.edge.base_path | quote }}
        ports:
        - name: proxy
          containerPort: 8080
        - name: metrics
          containerPort: 8081
        volumeMounts:
        - name: edge
          mountPath: {{ .Values.global.edge.certPath }}
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      imagePullSecrets:
      - name: docker.secret
      volumes:
      - name: edge
        secret:
          secretName: edge
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
