kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
      deployment: edge
  template:
    metadata:
      labels:
        app: edge
        deployment: edge
    spec:
      serviceAccountName: {{ .Values.global.spire.agent.serviceAccount.name }}
      initContainers:
        - name: ensure-spire-server
          image: deciphernow/k8s-waiter
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: spire-server
            - name: POST_DELAY
              value: "2"
      containers:
      - name: spire-agent
        image: {{ .Values.global.spire.agent.image }}
        args: ["-config", "/run/spire/config/agent.conf"]
        volumeMounts:
          - name: spire-config
            mountPath: /run/spire/config
            readOnly: true
          - name: spire-agent-socket
            mountPath: /run/spire/sockets
            readOnly: false
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "/opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock 2>&1 | grep -vqE 'connection refused|no such file or directory'"
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 3
      - name: edge
        image: {{ tpl .Values.sidecar.image $ | quote }}
        imagePullPolicy: {{ .Values.sidecar.imagePullPolicy }}
        {{- if .Values.edge.resources }}
        resources:
{{ toYaml .Values.edge.resources | indent 10 }}
        {{- end }}
        env:
        {{- include "greymatter.envvars" . | indent 8 }}
        ports:
        - name: proxy
          containerPort: 8080
        - name: metrics
          containerPort: 8081
        volumeMounts:
        - name: edge
          mountPath: {{ .Values.global.edge.certPath }}
        {{- if .Values.global.spire.enabled }}
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        {{- end }}
      imagePullSecrets:
      - name: docker.secret
      volumes:
      - name: edge
        secret:
          secretName: edge
      {{- if .Values.global.spire.enabled }}
      - name: spire-config
        configMap:
          name: spire-agent
      - name: spire-agent-socket
        emptyDir: {}
      {{- end }}