kind: Service
apiVersion: v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
  labels:
    gm.proxy: edge
spec:
  ports:
    - name: proxy
      port: 10808
    - name: metrics
      port: 8081
  selector:
    gm.proxy: edge
