kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
      deployment: edge
  template:
    metadata:
      labels:
        app: edge
        deployment: edge
    spec:
      containers:
      - name: edge
        image: {{ .Values.sidecar.image | quote }}
        imagePullPolicy: {{ .Values.sidecar.imagePullPolicy }}
        {{- if .Values.edge.resources }}
        resources:
{{ toYaml .Values.edge.resources | indent 10 }}
        {{- end }}
        env:
        {{- include "greymatter.envvars" . | indent 8 }}
        - name: ZK_ADDRS
          value: {{ template "greymatter.exhibitor.address" . }}
        - name: ZK_ANNOUNCE_PATH
          value: {{ .Values.edge.base_path | quote }}
        ports:
        - name: http
          containerPort: 8443
        - name: metrics
          containerPort: 8081
        volumeMounts:
        - name: edge
          mountPath: /etc/proxy/tls/edge
        - name: sidecar
          mountPath: /etc/proxy/tls/sidecar
      imagePullSecrets:
      - name: docker.secret
      volumes:
      - name: edge
        secret:
          secretName: edge
      - name: sidecar
        secret:
          secretName: sidecar
