{{- if and .Values.ingress_config.environment (eq .Values.ingress_config.environment "openshift") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  host: 
  {{- if eq .Values.ingress_config.remove_namespace_from_url "true" }}
    {{ .Values.ingress_config.route_url_name }}.{{ .Values.ingress_config.domain }}
  {{- else }}
    {{ .Values.ingress_config.route_url_name }}.{{ .Release.Namespace }}.{{ .Values.ingress_config.domain }}
  {{- end }}
  port: 
    targetPort: http
  tls:
    termination: passthrough
  to:
    kind: Service
    name: edge
    weight: 100
  wildcardPolicy: None
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq .Values.ingress_config.remove_namespace_from_url "true" }}
    - host: {{ .Values.ingress_config.route_url_name }}.{{ .Values.ingress_config.domain }}
  {{- else }}
    - host: {{ .Values.ingress_config.route_url_name }}.{{ .Release.Namespace }}.{{ .Values.ingress_config.domain }}
  {{- end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: edge
              servicePort: 8443
{{- end }}