kind: Service
apiVersion: v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
  labels:
    app: edge
spec:
  ports:
    - name: proxy
      port: 8080
    - name: metrics
      port: 8001
  selector:
    app: edge