kind: Service
apiVersion: v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
  labels:
    app: edge
spec:
  type: NodePort
  ports:
    - name: http
      port: 8443
      nodePort: 30443
    - name: metrics
      port: 8080
    - name: metrics
      port: 8001
  selector:
    app: edge
