apiVersion: v1
appVersion: 1.6.0-dev
description: A Helm chart to deploy a Grey Matter Proxy
name: proxy
version: 3.0.1
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh

