## Diff: No Voyager, No jwt, no data, redirects to local charts, not Nexus

dependencies:
<<<<<<< HEAD
  - name: catalog
    repository: 'file://../catalog'
    version: '1.0.3'

  - name: data
    repository: 'file://../data'
    version: '1.0.3'

  - name: dashboard
    repository: 'file://../dashboard'
    version: '1.0.3'

  - name: documentation
    repository: 'file://../documentation'
    version: '1.0.2'

  - name: edge
    repository: 'file://../edge'
    version: '1.0.5'

  # - name: xds
  #   repository: 'file://../xds'
  #   version: '1.0.2'

  - name: oldtown
    repository: 'file://../oldtown'
    version: '0.1.0'

  - name: control
    repository: 'file://../control'
    version: '0.1.0'

  # - name: exhibitor
  #   repository: 'file://../exhibitor'
  #   version: '1.0.1'

  - name: jwt
    repository: 'file://../jwt'
    version: '1.0.1'

  - name: slo
    repository: 'file://../slo'
    version: '1.0.2'
=======
- name: catalog
  version: "1.0.3"
  repository: "file://../catalog"

- name: dashboard
  version: "1.0.3"
  repository: "file://../dashboard"

- name: documentation
  version: "1.0.2"
  repository: "file://../documentation"

- name: edge
  version: "1.0.5"
  repository: "file://../edge"

- name: xds
  version: "1.0.2"
  repository: "file://../xds"

- name: exhibitor
  version: "1.0.1"
  repository: "file://../exhibitor"

- name: slo
  version: "1.0.2"
  repository: "file://../slo"
>>>>>>> removing PV claims and jwt
