## Diff: No Voyager, No jwt, no data, redirects to local charts, not Nexus

dependencies:
- name: catalog
  version: "1.0.3"
  repository: "file://../catalog"

- name: dashboard
  version: "1.0.3"
  repository: "file://../dashboard"

- name: documentation
  version: "1.0.2"
  repository: "file://../documentation"

- name: edge
  version: "1.0.5"
  repository: "file://../edge"

- name: xds
  version: "1.0.2"
  repository: "file://../xds"

- name: exhibitor
  version: "1.0.1"
  repository: "file://../exhibitor"

- name: slo
  version: "1.0.2"
  repository: "file://../slo"
