dependencies:
  - name: catalog
    version: '2.1.5'
    repository: 'file://../catalog'

  - name: data
    version: '2.1.4'
    repository: 'file://../data'
    alias: internal-data

  - name: data
    version: '2.1.4'
    repository: 'file://../data'

  - name: dashboard
    version: '2.1.2'
    repository: 'file://../dashboard'

  - name: edge
    version: '2.1.5'
    repository: 'file://../edge'

  - name: jwt
    version: '2.1.1'
    repository: 'file://../jwt'

  - name: jwt
    version: '2.1.1'
    repository: 'file://../jwt'
    alias: internal-jwt

  - name: slo
    version: '2.1.1'
    repository: 'file://../slo'
    

  - name: gm-control-api
    version: '2.1.5'
    repository: 'file://../gm-control-api'

  - name: control
    version: '2.1.3'
    repository: 'file://../control'

  - name: spire
    version: '2.1.1'
    repository: 'file://../spire'
    condition: global.spire2.enabled
