## Diff: No Voyager, No jwt, no data, redirects to local charts, not Nexus

dependencies:
- name: catalog
  version: "1.0.5"
  repository: "file://../catalog"

  - name: dashboard
    repository: 'file://../dashboard'
    version: '1.0.3'

- name: documentation
  version: "1.0.3"
  repository: "file://../documentation"

- name: edge
  version: "1.0.6"
  repository: "file://../edge"

- name: jwt
  version: "1.0.2"
  repository: "file://../jwt"

- name: slo
  version: "1.0.3"
  repository: "file://../slo"

- name: oldtown
  repository: 'file://../oldtown'
  version: '0.1.0'

- name: control
  repository: 'file://../control'
  version: '0.1.0'
