global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: false
  zone: default-zone
  catalog:
    version: 0.3.6
  dashboard:
    version: latest
  data:
    version: 0.2.3
  documentation:
    version: 3.0.0
  edge:
    version: 0.7.1
  exhibitor:
    replicas: 1
    version:
  jwt:
    version: 0.2.0
  slo:
    version: 0.4.0
  xds:
    cluster: greymatter
    port: 18000
    version: 0.2.6
  services:
    catalog:
      name: 'Grey Matter Catalog'
      serviceName: 'catalog'
      routes:
        - '/services/catalog/{{ $.Values.global.catalog.version }}'
        - '/services/catalog/{{ $.Values.global.catalog.version }}/'

    # control:
    #   name: 'Grey Matter Control'
    #   serviceName: 'control'
    #   routes:
        # - '/services/xds/{{ $.Values.global.xds.version }}'
        # - '/services/xds/{{ $.Values.global.xds.version }}'

    dashboard:
      name: 'Grey Matter Dashboard'
      serviceName: 'dashboard'
      routes:
        - '/services/dashboard/latest'
        - '/services/dashboard/latest/'

    data:
      name: 'Grey Matter Data'
      serviceName: 'data'
      routes:
        - '/services/data/{{ $.Values.global.data.version }}'
        - '/services/data/{{ $.Values.global.data.version }}/'

    jwt:
      name: 'Grey Matter JWT Security'
      serviceName: 'jwt-security'
      routes:
        - '/services/jwt-security/{{ $.Values.global.jwt.version }}'
        - '/services/jwt-security/{{ $.Values.global.jwt.version }}/'

    edge:
      name: 'Grey Matter Edge'
      serviceName: 'edge'
      routes:
        - '/' #/services/edge/{{ $.Values.global.edge.version }}
        # - '/' #/services/edge/{{ $.Values.global.edge.version }}
    # TODO: multiple routes

    slo:
      name: 'Grey Matter Service Level Objectives'
      serviceName: 'slo'
      routes:
        - '/services/slo/{{ $.Values.global.slo.version }}'
        - '/services/slo/{{ $.Values.global.slo.version }}/'

    documentation:
      name: 'Grey Matter Documentation'
      serviceName: 'documentation'
      routes:
        - '/services/documentation/{{ $.Values.global.documentation.version }}'
        - '/services/documentation/{{ $.Values.global.documentation.version }}/'

  # sidecar:
  #   envvars:
  # All of the mesh-wide environment variables should be set in your `custom.yaml` file

sidecar:
  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: true
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
