global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: false
  catalog:
    version: 0.3.6
  dashboard:
    version: latest
  data:
    version: 0.2.3
  documentation:
    version: 3.0.0
  edge:
    version: 0.7.1
  exhibitor:
    replicas: 1
    version:
  jwt:
    version: 0.2.0
  slo:
    version: 0.4.0
  xds:
    cluster: greymatter
    port: 18000
    version: 0.2.6
  oldtown:
    version: latest
  control:
    version: latest
  sidecar:
    envvars:
      # These are sorted by how different the values are for the sidecars running on different services. The options are "all the same", "all except XDS". and "different"
      # TODO: update each service to use default global values and only set the ones that are different.
      # All the same
      ingress_use_tls:
        type: value
        value: 'true'
      ingress_ca_cert_path:
        type: value
        value: '/etc/proxy/tls/sidecar/ca.crt'
      ingress_cert_path:
        type: value
        value: '/etc/proxy/tls/sidecar/server.crt'
      ingress_key_path:
        type: value
        value: '/etc/proxy/tls/sidecar/server.key'
      metrics_key_function:
        type: value
        value: 'depth'
      service_host:
        type: value
        value: '127.0.0.1'
      obs_enabled:
        type: value
        value: 'false'
      obs_full_response:
        type: value
        value: 'false'
      obs_enforce:
        type: value
        value: 'false'
      kafka_enabled:
        type: value
        value: 'false'
      kafka_zk_discover:
        type: value
        value: 'false'
      kafka_server_connection:
        type: value
        value: 'kafka:9091,kafka2:9091'
      # All except XDS
      metrics_port:
        type: value
        value: '8081'
      proxy_dynamic:
        type: value
        value: 'true'
      # Different
      port:
        type: value
        value: ''
      service_port:
        type: value
        value: ''
      kafka_topic:
        type: value
        value: ''
      zk_addrs:
        type: value
        value: ''
      zk_announce_path:
        type: value
        value: ''
      egress_use_tls:
        type: value
        value: ''
      egress_ca_cert_path:
        type: value
        value: ''
      egress_cert_path:
        type: value
        value: ''
      egress_key_path:
        type: value
        value: ''
      # There may be more sidecar environment variables, but we haven't added them here yet.
      # However, to use an env var with the sidecar, even if it doesn't have a global default,
      # it needs to be set globally as either a value or a secret

sidecar:
  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: true
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
