{{ if .Values.jwt.certificates }}
{{- range $certs := .Values.jwt.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $certs.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  {{- range $key, $value := $certs }}
  {{- if and (ne $key "name") }}
  {{ base $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end  }}
{{- end }}
{{- end }}