apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses:
      name: helm-package
      namespace: jenkins
      kind: DeploymentConfig
  name: helm-package
spec:
  source:
    git:
      ref: SETBRANCH
      uri: https://github.com/DecipherNow/helm-charts.git
    type: Git
    sourceSecret:
      name: github-clone
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: ci/Jenkinsfile
  triggers:
    - github:
        secretReference:
          name: github
type: GitHub