apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit-config
    namespace: {{ .Release.Namespace }}
    labels:
        app: fluent-bit
data:
    fluent-bit.conf: |
        [SERVICE]
            Flush 1
            Daemon Off
            Log_Level info
            Parsers_File parsers.conf
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Exclude_Path /var/log/containers/fluent*,/var/log/containers/lad*,/var/log/containers/lass*
            Parser docker
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
        [OUTPUT]
            Name http
            Host lad.default.svc.cluster.local
            Port 8080
            URI /logs/fluent
            Format json_lines
            Match *