apiVersion: v1
kind: Service
metadata:
  name: lad
  namespace: {{ .Release.Namespace }}
  labels:
    app: lad
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: lad
      protocol: TCP
      name: http
  selector:
    {{ .Values.global.control.cluster_label }}: lad