apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lad
spec:
  serviceName: lad
  selector:
    matchLabels:
      greymatter.io/control: lad
  template:
    metadata:
      labels:
        greymatter.io/control: lad
    spec:
      volumes:
        - name: spire-socket
          hostPath:
            path: /run/spire/socket
            type: DirectoryOrCreate
      imagePullSecrets:
      - name: docker.secret
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0


      containers:
      - name: lad
        image: docker.greymatter.io/internal/sense-lad:latest
        imagePullPolicy: Always
        ports:
          - name: lad
            containerPort: 8080
        env:
          - name: LAD_INFERENCE_THREADS
            value: '3'
          - name: LAD_TRAINING_THREADS
            value: '3'
        resources:
          limits:
            cpu: '4'
            memory: 5Gi
          requests:
            cpu: '2'
            memory: 2Gi
        volumeMounts:
          - name: lad-storage
            mountPath: "/app/storage"

      - name: sidecar
        image: docker.greymatter.io/release/gm-proxy:1.5.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: proxy
            containerPort: 10808
          - name: metrics
            containerPort: 8081
        env:
          - name: ENVOY_ADMIN_LOG_PATH
            value: /dev/stdout
          - name: PROXY_DYNAMIC
            value: "true"
          - name: XDS_CLUSTER
            value: lad
          - name: XDS_HOST
            value: control.default.svc
          - name: XDS_PORT
            value: "50000"
          - name: XDS_NODE_ID
            value: default
          - name: XDS_ZONE
            value: "zone-default-zone"
          - name: SPIRE_PATH
            value: /run/spire/socket/agent.sock
        volumeMounts:
          - name: spire-socket
            mountPath: /run/spire/socket
  volumeClaimTemplates:
    - metadata:
        name: lad-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        volumeMode: Filesystem