dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: '7.5.1'
  - name: logstash
    repository: https://helm.elastic.co
    version: '7.5.1'
  - name: kibana
    repository: https://helm.elastic.co
    version: '7.5.1'
  - name: kafka
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    version: '0.20.7'
  - name: zookeeper
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    version: '2.1.3'
#   - name: 
#     repository:
#     version:
#   - name: 
#     repository:
#     version: