name: Lint Charts

on:
  push:
    # We don't need to lint on a push to the release branch as this
    # only happen after a merge
    branches:
      - "!release-*"

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      
      - name: Run chart-testing ( lint edge and secrets)
        run: ct lint --config .chart-testing/edge-secrets.yaml

      - name: Run chart-testing (lint services)
        run: ct lint --config .chart-testing/services.yaml

  lint-umbrella-charts:
    runs-on: ubuntu-latest
    needs: lint-charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed2
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Helm dep up parent Charts
        run: helm dep up fabric sense data spire

      - name: Run chart-testing (lint fabric sense data)
        run: ct lint --config .chart-testing/fabric-sense-data.yaml

