apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.control.name }}
    {{ .Values.global.control.cluster_label }}: {{ .Values.control.name }}
  name: {{ .Values.control.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: control-sidecar
    port: {{ .Values.global.control.port }}
    protocol: TCP
    targetPort: grpc
  - name: control
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    run: {{ .Values.control.name }}
  type: ClusterIP
