apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.control.name }}
    {{ .Values.global.control.cluster_label }}: {{ .Values.control.name }}
  name: {{ .Values.control.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.global.control.port }}
    protocol: TCP
    targetPort: grpc
  - name: admin
    port: {{ .Values.global.control.admin_port }}
    protocol: TCP
    targetPort: admin
  selector:
    run: {{ .Values.control.name }}
  type: ClusterIP
