---
apiVersion: v1
kind: ConfigMap
metadata:
  name: control-sidecar
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    node:
      id: "default"
      cluster: "fabric.control"
    static_resources:
      listeners:
        - name: egress
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 9080
          filter_chains:
            - filters:
              - name: envoy.http_connection_manager
                config:
                  forward_client_cert_details: sanitize_set
                  set_current_client_cert_details:
                      uri: true
                  codec_type: auto
                  access_log:
                    - name: envoy.file_access_log
                      config:
                        path: "/dev/stdout"
                  stat_prefix: egress
                  route_config:
                    name: api
                    virtual_hosts:
                      - name: local
                        domains:
                          - "*"
                        routes:
                          - match:
                              prefix: "/"
                            route:
                              cluster: api
                  http_filters:
                    - name: envoy.router
        - name: ingress
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 10808
          filter_chains:
            - filters:
              - name: envoy.http_connection_manager
                config:
                  forward_client_cert_details: sanitize_set
                  set_current_client_cert_details:
                      uri: true
                  codec_type: auto
                  access_log:
                    - name: envoy.file_access_log
                      config:
                        path: "/dev/stdout"
                  stat_prefix: ingress
                  route_config:
                    name: local
                    virtual_hosts:
                      - name: local
                        domains:
                          - "*"
                        routes:
                          - match:
                              prefix: "/"
                            route:
                              cluster: local
                  http_filters:
                    - name: envoy.router
              tls_context:
                common_tls_context:
                    {{- if .Values.global.spire.enabled }}
                    tls_certificate_sds_secret_configs:
                        - name: "spiffe://{{ .Values.global.spire.trust_domain }}"
                        sds_config:
                            api_config_source:
                            api_type: GRPC
                            grpc_services:
                                envoy_grpc:
                                cluster_name: spire
                    tls_params:
                        ecdh_curves:
                        - X25519:P-256:P-521:P-384
                    validation_context_sds_secret_config:
                        name: "spiffe://{{ .Values.global.spire.trust_domain }}"
                        sds_config:
                        api_config_source:
                            api_type: GRPC
                            grpc_services:
                            envoy_grpc:
                                cluster_name: spire
                    {{- else }}
                    tls_certificates:
                        - certificate_chain: /etc/proxy/tls/sidecar/server.crt
                            private_key: /etc/proxy/tls/sidecar/server.key
                    validation_context:
                        trusted_ca:
                            filename: /etc/proxy/tls/sidecar/ca.crt
                    {{- end }}
      clusters:
        - name: api
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: api
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: api.fabric.svc.cluster.local
                        port_value: 10808
          tls_context:
            common_tls_context:
                {{- if .Values.global.spire.enabled }}
                tls_certificate_sds_secret_configs:
                - name: "spiffe://{{ .Values.global.spire.trust_domain }}"
                    sds_config:
                    api_config_source:
                        api_type: GRPC
                        grpc_services:
                        envoy_grpc:
                            cluster_name: spire
                tls_params:
                ecdh_curves:
                    - X25519:P-256:P-521:P-384
                validation_context_sds_secret_config:
                name: "spiffe://{{ .Values.global.spire.trust_domain }}"
                sds_config:
                    api_config_source:
                    api_type: GRPC
                    grpc_services:
                        envoy_grpc:
                        cluster_name: spire
                {{- else }}
                tls_certificates:
                - certificate_chain: /etc/proxy/tls/sidecar/server.crt
                    private_key: /etc/proxy/tls/sidecar/server.key
                validation_context:
                trusted_ca:
                    filename: /etc/proxy/tls/sidecar/ca.crt
                {{- end }}
        - name: local
          connect_timeout: 5s
          http2_protocol_options: {}
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: local
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 127.0.0.1
                        port_value: 50000
        {{- if .Values.global.spire.enabled }}
        - name: spire
          connect_timeout: 5s
          http2_protocol_options: {}
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: spire
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      pipe:
                        path: {{ .Values.global.spire.path }}
        {{- end }}
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001